<?php

/**
 * @file
 * Contains linda_formatuje.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function linda_formatuje_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linda_formatuje module.
    case 'help.page.linda_formatuje':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Úpravy šité na míru Lindě') . '</p>';
      return $output;

    default:
  }
}
