<?php

/**
 * @file
 * Contains linda_formatuje.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function linda_formatuje_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linda_formatuje module.
    case 'help.page.linda_formatuje':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>Úpravy šité na míru Lindě</p>';
      return $output;

    default:
  }
}

/**
 * Custom order twig templates
 * @param array $theme_registry
 */
function linda_formatuje_theme_registry_alter(&$theme_registry) {
	$theme_registry['commerce_checkout_completion_message']['path'] = drupal_get_path('module', 'linda_formatuje') . '/templates';
// 	$theme_registry['commerce_order_receipt']['path'] = drupal_get_path('module', 'linda_formatuje') . '/templates';
}